name: Ingest iNat and Score • vENVDEBUG_POOLER_IPV4

on:
  workflow_dispatch:
  # Uncomment later if you want automation
  # schedule:
  #   - cron: "*/30 * * * *"
  push:
    paths:
      - ".github/workflows/ingest-and-score.yml"
      - "ingest.mjs"
      - "sql/**"

permissions:
  contents: read

concurrency:
  group: ingest-and-score
  cancel-in-progress: true

jobs:
  ingest-and-score:
    runs-on: ubuntu-latest

    # HTTP API (ingest.mjs) + iNat knobs
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      INAT_BASE: ${{ secrets.INAT_BASE }}
      ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}
      RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (ok if none)
        shell: bash
        run: |
          set -e
          if [ -f package-lock.json ]; then npm ci
          elif [ -f package.json ]; then npm i
          else echo "No package.json found; skipping"
          fi

      - name: Run iNat ingestion script
        shell: bash
        run: |
          set -euo pipefail
          node -v
          node ingest.mjs

      - name: Install psql client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client dnsutils

      - name: Debug (shell) — DB secrets presence
        shell: bash
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SUPABASE_POOL_URL: ${{ secrets.SUPABASE_POOL_URL }}
        run: |
          set -e
          for k in SUPABASE_DB_URL SUPABASE_POOL_URL; do
            if [ -n "${!k:-}" ]; then echo "$k: SET"; else echo "$k: (missing)"; fi
          done

      # ── Prefer pooler; fallback to direct. Force IPv4 via hostaddr= ─────────────
      - name: Choose DB URL and handshake (IPv4, verbose)
        id: pickdb
        shell: bash
        env:
          DB_URL_DIRECT: ${{ secrets.SUPABASE_DB_URL }}
          DB_URL_POOL:   ${{ secrets.SUPABASE_POOL_URL }}
        run: |
          set -euo pipefail

          parse_url () {
            # $1=url ; outputs: URL_USER URL_PASS URL_HOST URL_PORT URL_DB
            local url="$1" rest user pass hostport host port path db
            rest="${url#*://}"                 # user:pass@host:port/db?query
            user="${rest%%:*}"                 # user
            rest="${rest#*:}"                  # pass@host:port/db?query
            pass="${rest%%@*}"                 # pass
            rest="${rest#*@}"                  # host:port/db?query
            hostport="${rest%%/*}"             # host:port
            path="${rest#*/}"                  # db?query
            host="${hostport%%:*}"             # host
            port="${hostport#*:}"; [ "$port" = "$hostport" ] && port="5432"
            db="${path%%\?*}"                  # db
            printf '%s\n' "$user" "$pass" "$host" "$port" "$db"
          }

          try_ipv4 () {
            # $1=url ; $2=label
            local url="$1" label="$2"
            echo "::group::Handshake: $label"
            read -r URL_USER URL_PASS URL_HOST URL_PORT URL_DB < <(parse_url "$url")

            echo "Host      : $URL_HOST"
            echo "Port      : $URL_PORT"
            echo "DB        : $URL_DB"
            echo "User      : $URL_USER"
            echo "PGSSLMODE : require"

            # Resolve IPv4 A record
            IPv4="$(dig +short A "$URL_HOST" | head -1 || true)"
            if [ -z "$IPv4" ]; then
              echo "::warning::No IPv4 A-record for $URL_HOST (runner may be IPv4-only)."
              echo "::endgroup::"
              return 1
            fi
            echo "IPv4      : $IPv4"

            # Socket test (5s)
            if timeout 5 bash -c ">/dev/tcp/$IPv4/$URL_PORT" 2>/dev/null; then
              echo "TCP check : OK"
            else
              echo "::warning::TCP to $IPv4:$URL_PORT failed."
              echo "::endgroup::"
              return 1
            fi

            # Connect with hostaddr to force IPv4
            export PGPASSWORD="$URL_PASS" PGSSLMODE=require
            DSN="hostaddr=$IPv4 host=$URL_HOST port=$URL_PORT dbname=$URL_DB user=$URL_USER sslmode=require"
            if psql "$DSN" -v VERBOSITY=verbose -Atc "select 1" ; then
              echo "psql      : OK"
              echo "::endgroup::"
              return 0
            else
              echo "::warning::psql failed for $label."
              echo "::endgroup::"
              return 1
            fi
          }

          USE_URL=""
          if [ -n "${DB_URL_POOL:-}" ] && try_ipv4 "$DB_URL_POOL" "Pooler (6543)"; then
            USE_URL="$DB_URL_POOL"
          elif [ -n "${DB_URL_DIRECT:-}" ] && try_ipv4 "$DB_URL_DIRECT" "Direct (5432)"; then
            USE_URL="$DB_URL_DIRECT"
          else
            echo "::error title=DB handshake::Could not reach either DB URL from GitHub Actions."
            echo "Hints:"
            echo "  • Verify both secrets are exact Supabase URIs ending with '?sslmode=require'"
            echo "  • Supabase project running (not paused) and no region/name typos"
            echo "  • Network Restrictions are open (or include GitHub’s egress)"
            exit 2
          fi

          echo "use_url=$USE_URL" >> "$GITHUB_OUTPUT"
          echo "USE_URL=$USE_URL" >> "$GITHUB_ENV"

      - name: Generate SQL with correct id column
        id: gensql
        shell: bash
        env:
          USE_URL: ${{ steps.pickdb.outputs.use_url }}
        run: |
          set -euo pipefail
          check_col () { psql "$USE_URL" -Atc "select 1 from information_schema.columns \
            where table_schema='public' and table_name='daily_scores' and column_name='$1'" | grep -q 1; }

          if check_col student_id; then ID_COL=student_id
          elif check_col roster_id; then ID_COL=roster_id
          elif check_col person_id; then ID_COL=person_id
          else
            echo "::error title=Missing id column::daily_scores must have one of: student_id, roster_id, person_id"
            exit 1
          fi

          echo "Detected ID_COL=${ID_COL}"
          sed -e "s/__ID_COL__/${ID_COL}/g" \
            sql/leaderboard_views.template.sql > sql/_gen_leaderboard_views.sql

      - name: Apply / update views (idempotent)
        shell: bash
        env:
          USE_URL: ${{ steps.pickdb.outputs.use_url }}
        run: |
          set -euo pipefail
          echo "Connection info:"
          psql "$USE_URL" -Atc "select current_user, current_database(), inet_client_addr()"
          echo "Applying SQL…"
          psql "$USE_URL" -v ON_ERROR_STOP=1 -f sql/_gen_leaderboard_views.sql
