name: Ingest iNaturalist Data and Score

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  data-pipeline:
    name: Fetch, Ingest, and Process Data
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js LTS (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      # =================================================================
      # CRITICAL FIX: Comprehensive Variable Aliasing
      # The script errors indicate it is looking for non-standard variable names
      # (e.g., DATABASE_URL, framework prefixes, or generic keys).
      # =================================================================
      - name: Create .env file from Secrets (Quoted and Aliased)
        run: |
          echo "Synthesizing .env file with robust quoting and comprehensive variable mapping..."
          # Format: KEY="VALUE" (Quoting handles special characters)

          # Capture secrets into local variables for cleaner reuse
          S_URL="${{ secrets.SUPABASE_URL }}"
          S_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
          POOLER_URL="${{ secrets.SUPABASE_POOL_URL }}"

          # --- Supabase SDK Variables ---
          # Standard backend names
          printf "SUPABASE_URL=\"%s\"\n" "$S_URL" > .env
          printf "SUPABASE_SERVICE_ROLE_KEY=\"%s\"\n" "$S_KEY" >> .env

          # CRITICAL FIX: Common Aliases and Framework conventions (Next.js, Vite)
          # Alias Service Key as generic KEY and ANON_KEY
          printf "SUPABASE_KEY=\"%s\"\n" "$S_KEY" >> .env
          printf "SUPABASE_ANON_KEY=\"%s\"\n" "$S_KEY" >> .env

          # Prefixed conventions
          printf "NEXT_PUBLIC_SUPABASE_URL=\"%s\"\n" "$S_URL" >> .env
          printf "NEXT_PUBLIC_SUPABASE_ANON_KEY=\"%s\"\n" "$S_KEY" >> .env
          printf "VITE_SUPABASE_URL=\"%s\"\n" "$S_URL" >> .env
          printf "VITE_SUPABASE_ANON_KEY=\"%s\"\n" "$S_KEY" >> .env

          # --- Database Connection Variables (Using the Pooler URL) ---
          # Supabase-specific and Conventional names (PostgreSQL/Prisma)
          printf "SUPABASE_DB_URL=\"%s\"\n" "$POOLER_URL" >> .env
          printf "DATABASE_URL=\"%s\"\n" "$POOLER_URL" >> .env
          printf "POSTGRES_URL=\"%s\"\n" "$POOLER_URL" >> .env

          # --- iNaturalist and Application variables ---
          printf "INAT_BASE=\"%s\"\n" "${{ secrets.INAT_BASE }}" >> .env
          printf "ASSIGNMENT_IDS=\"%s\"\n" "${{ secrets.ASSIGNMENT_IDS }}" >> .env
          printf "RATE_LIMIT_RPS=\"%s\"\n" "${{ secrets.RATE_LIMIT_RPS }}" >> .env
          printf "NODE_ENV=\"production\"\n" >> .env

          echo ".env file created successfully."

      # Optional Diagnostic
      - name: Verify .env file structure (Masked)
        run: cat .env

      # =================================================================
      # Execution Step (Using forced preloading)
      # =================================================================
      - name: Run Data Ingestion
        # Force loading the .env file before the script starts
        run: node -r dotenv/config ingest.mjs
