name: Ingest and Score New Observations

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  ingest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ecology-bioblitz-scoring

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'ecology-bioblitz-scoring'

      # --- FIX: Added Node.js setup step ---
      # This ensures a consistent version of Node.js and npm are available.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create .env file from secrets
        run: |
          echo "Creating .env file..."
          printf "SUPABASE_DB_URL=\"%s\"\n" "${{ secrets.SUPABASE_POOL_URL }}" >> .env
          printf "INAT_BASE=\"%s\"\n" "${{ secrets.INAT_BASE }}" >> .env
          printf "ASSIGNMENT_IDS=\"%s\"\n" "${{ secrets.ASSIGNMENT_IDS }}" >> .env
          printf "RATE_LIMIT_RPS=\"%s\"\n" "${{ secrets.RATE_LIMIT_RPS }}" >> .env
          printf "NODE_ENV=\"production\"\n" >> .env
          echo ".env file created successfully."

      - name: Verify .env file structure (Masked)
        run: cat .env

      - name: Install dependencies
        run: npm install

      - name: Run Data Ingestion
        run: node -r dotenv/config ingest.mjs
