name: Ingest iNat and Score (ipv4 simple)

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/30 * * * *"
  push:
    paths:
      - ".github/workflows/ingest-and-score.yml"
      - "ingest.mjs"
      - "sql/**"

permissions:
  contents: read

concurrency:
  group: ingest-and-score
  cancel-in-progress: true

jobs:
  ingest-and-score:
    runs-on: ubuntu-latest

    env:
      # HTTP API (used by ingest.mjs)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # iNat knobs
      INAT_BASE: ${{ secrets.INAT_BASE }}
      ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}
      RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (ok if none)
        shell: bash
        run: |
          set -e
          if [ -f package-lock.json ]; then npm ci
          elif [ -f package.json ]; then npm i
          else echo "No package.json found; skipping"
          fi

      - name: Run iNat ingestion script
        shell: bash
        run: |
          set -euo pipefail
          node ingest.mjs

      - name: Install psql client
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client dnsutils

      - name: Debug (shell) - DB secrets presence
        shell: bash
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SUPABASE_POOL_URL: ${{ secrets.SUPABASE_POOL_URL }}
        run: |
          set -e
          for k in SUPABASE_DB_URL SUPABASE_POOL_URL; do
            if [ -n "${!k:-}" ]; then echo "$k: SET"; else echo "$k: (missing)"; fi
          done

      - name: Choose DB URL and handshake (IPv4, verbose)
        id: pickdb
        shell: bash
        env:
          DB_URL_DIRECT: ${{ secrets.SUPABASE_DB_URL }}
          DB_URL_POOL:   ${{ secrets.SUPABASE_POOL_URL }}
        run: |
          set -euo pipefail

          parse () { python3 - "$1" <<'PY'
import sys, urllib.parse as U
u = U.urlparse(sys.argv[1])
print(u.username or '')
print(u.password or '')
print(u.hostname or '')
print(str(u.port or 5432))
print((u.path or '/').lstrip('/').split('/')[0])
PY
          }

          try_v4 () {
            url="$1"; label="$2"
            [ -z "${url:-}" ] && { echo "::warning::Empty URL for $label"; return 1; }

            read -r U P H PORT DB < <(parse "$url")
            echo "Handshake: $label"
            echo " host=$H port=$PORT db=$DB user=$U"

            IPv4="$(dig +short A "$H" | head -1 || true)"
            if [ -z "$IPv4" ]; then
              echo "::warning::No IPv4 A-record for $H"; return 1
            fi
            echo " ipv4=$IPv4"

            export PGPASSWORD="$P" PGSSLMODE=require
            DSN="hostaddr=$IPv4 host=$H port=$PORT dbname=$DB user=$U sslmode=require"
            if psql "$DSN" -v VERBOSITY=verbose -Atc "select 1"; then
              echo "psql: OK"
              echo "$url"
              return 0
            else
              echo "::warning::psql failed for $label"
              return 1
            fi
          }

          USE_URL=""
          # Prefer pooler first (6543), then direct (5432)
          if [ -n "${DB_URL_POOL:-}" ] && USE_URL="$(try_v4 "$DB_URL_POOL" "Pooler (6543)")"; then :
          elif [ -n "${DB_URL_DIRECT:-}" ] && USE_URL="$(try_v4 "$DB_URL_DIRECT" "Direct (5432)")"; then :
          else
            echo "::error title=DB handshake::Could not reach either DB URL from GitHub Actions."
            echo "Hints:"
            echo "  • Secrets must be exact Supabase URIs and include '?sslmode=require'"
            echo "  • Project must be running (not paused)"
            echo "  • Network Restrictions should allow GitHub egress"
            exit 2
          fi

          echo "use_url=$USE_URL" >> "$GITHUB_OUTPUT"
          echo "USE_URL=$USE_URL" >> "$GITHUB_ENV"

      - name: Generate SQL with correct id column
        id: gensql
        shell: bash
        env:
          USE_URL: ${{ steps.pickdb.outputs.use_url }}
        run: |
          set -euo pipefail
          check_col () { psql "$USE_URL" -Atc "select 1 from information_schema.columns where table_schema='public' and table_name='daily_scores' and column_name='$1'" | grep -q 1; }

          if check_col student_id; then ID_COL=student_id
          elif check_col roster_id; then ID_COL=roster_id
          elif check_col person_id; then ID_COL=person_id
          else
            echo "::error title=Missing id column::daily_scores must have one of: student_id, roster_id, person_id"
            exit 1
          fi

          echo "Detected ID_COL=$ID_COL"
          sed -e "s/__ID_COL__/${ID_COL}/g" sql/leaderboard_views.template.sql > sql/_gen_leaderboard_views.sql

      - name: Apply or update views
        shell: bash
        env:
          USE_URL: ${{ steps.pickdb.outputs.use_url }}
        run: |
          set -euo pipefail
          echo "Connection info:"
          psql "$USE_URL" -Atc "select current_user, current_database(), inet_client_addr()"
          echo "Applying SQL..."
          psql "$USE_URL" -v ON_ERROR_STOP=1 -f sql/_gen_leaderboard_views.sql
