name: Ingest iNat and Score • vENVDEBUG6_MIN

on: { workflow_dispatch: {} }

permissions: { contents: read }

concurrency:
  group: ingest-and-score
  cancel-in-progress: true

jobs:
  ingest-and-score:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Sanity echo
        run: echo "Workflow parses and runs ✔"
