name: Ingest iNaturalist Data and Score

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  data-pipeline:
    name: Fetch, Ingest, and Process Data
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Environment Configuration (Ensures secrets are passed to the script)
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_POOL_URL }} # Using Pooler URL
      INAT_BASE: ${{ secrets.INAT_BASE }}
      ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}
      RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # =================================================================
      # CRITICAL FORENSIC DIAGNOSTIC
      # This step MUST appear in the execution log.
      # =================================================================
      - name: Forensic File System Diagnostic
        run: |
          echo "Current directory: $(pwd)"
          echo "--------------------------------------------------"
          echo "Listing all files recursively (ls -R):"
          # This command lists ALL files in the repository, revealing structure and capitalization.
          ls -R
          echo "--------------------------------------------------"
          echo "Checking for package.json at the root:"
          if [ -f "package.json" ]; then
            echo "SUCCESS: File exists at the root."
            # Check file encoding/type in case Web UI introduced errors
            echo "File type information:"
            file package.json
          else
            echo "::error::FAILURE: package.json NOT found in the ROOT directory. Review the 'ls -R' output above. If it is in a subdirectory, the workflow requires a 'working-directory' configuration. If it is missing entirely, it is not committed to this branch."
            # Fail the workflow immediately if the prerequisite file is missing
            exit 1
          fi
      # =================================================================

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # Caching disabled as package-lock.json is missing.

      - name: Install dependencies
        # Using 'npm install' as 'npm ci' requires package-lock.json.
        run: npm install

      - name: Run Data Ingestion
        run: node ingest.mjs
