name: Ingest iNaturalist Data and Score

on:
  workflow_dispatch: # Allows manual triggering
  # schedule:
  #   - cron: '0 2 * * *' # Uncomment for scheduled runs

# Security Best Practice
permissions:
  contents: read

jobs:
  # We use a consistent job ID and name
  data-pipeline:
    name: Fetch, Ingest, and Process Data
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # =================================================================
    # CRITICAL FIX: Environment Configuration
    # This block is required to pass secrets to the Node.js script.
    # If this block is missing, the script will fail with "Missing required environment variables."
    # =================================================================
    env:
      # Supabase API Access
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # Database Connection String (Using the working Pooler URL)
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_POOL_URL }}

      # iNaturalist Configuration
      INAT_BASE: ${{ secrets.INAT_BASE }}
      ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}

      # Application Settings
      RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js LTS (v20)
        uses: actions/setup-node@v4
        with:
          # FIX: Upgrading to Node 20 to resolve the deprecation warning.
          node-version: '20.x'

      - name: Install dependencies
        # Using 'npm install' because package-lock.json is missing.
        run: npm install

      - name: Run Data Ingestion
        run: node ingest.mjs
