name: Ingest iNat and Score (ipv4 simple)

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/30 * * * *"
  push:
    paths:
      - ".github/workflows/ingest-and-score.yml"
      - "ingest.mjs"
      - "sql/**"

permissions:
  contents: read

concurrency:
  group: ingest-and-score
  cancel-in-progress: true

jobs:
  ingest-and-score:
    runs-on: ubuntu-latest

    env:
      # HTTP API (used by ingest.mjs)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # iNat knobs
      INAT_BASE: ${{ secrets.INAT_BASE }}
      ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}
      RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (ok if none)
        shell: bash
        run: |
          set -e
          if [ -f package-lock.json ]; then npm ci
          elif [ -f package.json ]; then npm i
          else echo "No package.json found; skipping"
          fi

      - name: Run iNat ingestion script
        shell: bash
        run: |
          set -euo pipefail
          node ingest.mjs

      - name: Install psql client
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client dnsutils

      - name: Debug (shell) - DB secrets presence
        shell: bash
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SUPABASE_POOL_URL: ${{ secrets.SUPABASE_POOL_URL }}
        run: |
          set -e
          for k in SUPABASE_DB_URL SUPABASE_POOL_URL; do
            if [ -n "${!k:-}" ]; then echo "$k: SET"; else echo "$k: (missing)"; fi
          done

      - name: Choose DB URL and handshake (simple)
        id: pickdb
        shell: bash
        env:
          DB_URL_DIRECT: ${{ secrets.SUPABASE_DB_URL }}
          DB_URL_POOL: ${{ secrets.SUPABASE_POOL_URL }}
        run: |
          set -euo pipefail

          try_url () {
            url="$1"; label="$2"
            echo "::group::Handshake: $label"
            if [ -z "${url:-}" ]; then
              echo "URL empty for $label"
              echo "::endgroup::"
              return 1
            fi

            # Quick connection test
            if psql "$url" -Atc "select 1" >/dev/null 2>&1; then
              echo "psql: OK for $label"
              echo "use_url=$url" >> "$GITHUB_OUTPUT"
              echo "::endgroup::"
              return 0
            fi

            echo "psql: FAILED for $label"
            host=$(printf '%s' "$url" | sed -E 's#^[^/]+://[^@]*@([^:/?]+).*#\1#')
            port=$(printf '%s' "$url" | sed -nE 's#.*:([0-9]+)/.*#\1#p')
            port=${port:-5432}

            echo "Host parsed : $host"
            echo "Port parsed : $port"
            echo "dig A       :"
            dig +short A "$host" || true
            echo "::endgroup::"
            return 1
          }

          # Prefer pooler (6543), then direct (5432)
          if try_url "${DB_URL_POOL:-}" "Pooler (6543)"; then
            :
          elif try_url "${DB_URL_DIRECT:-}" "Direct (5432)"; then
            :
          else
            echo "::error title=DB handshake::Could not reach either DB URL from GitHub Actions."
            echo "Hints:"
            echo "  - Secrets must be exact Supabase URIs and include ?sslmode=require"
            echo "  - Project must be running (not paused)"
            echo "  - Network Restrictions should allow GitHub egress"
            exit 2
          fi

      - name: Generate SQL with correct id column
        id: gensql
        shell: bash
        env:
          USE_URL: ${{ steps.pickdb.outputs.use_url }}
        run: |
          set -euo pipefail
          check_col () { psql "$USE_URL" -Atc "select 1 from information_schema.columns where table_schema='public' and table_name='daily_scores' and column_name='$1'" | grep -q 1; }

          if check_col student_id; then ID_COL=student_id
          elif check_col roster_id; then ID_COL=roster_id
          elif check_col person_id; then ID_COL=person_id
          else
            echo "::error title=Missing id column::daily_scores must have one of: student_id, roster_id, person_id"
            exit 1
          fi

          echo "Detected ID_COL=$ID_COL"
          sed -e "s/__ID_COL__/${ID_COL}/g" sql/leaderboard_views.template.sql > sql/_gen_leaderboard_views.sql

      - name: Apply or update views
        shell: bash
        env:
          USE_URL: ${{ steps.pickdb.outputs.use_url }}
        run: |
          set -euo pipefail
          echo "Connection info:"
          psql "$USE_URL" -Atc "select current_user, current_database(), inet_client_addr()"
          echo "Applying SQL..."
          psql "$USE_URL" -v ON_ERROR_STOP=1 -f sql/_gen_leaderboard_views.sql
