name: Ingest and Score New Observations

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  ingest:
    runs-on: ubuntu-latest

    # =================================================================
    # FIX: Set a default working directory for all subsequent 'run' steps.
    # This ensures commands execute inside the checked-out repository.
    # =================================================================
    defaults:
      run:
        working-directory: ./ecology-bioblitz-scoring

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Check out the code into a predictable directory name
          path: 'ecology-bioblitz-scoring'

      - name: Create .env file from secrets
        run: |
          echo "Creating .env file..."
          # Using printf to handle special characters in the Pooler URL
          printf "SUPABASE_DB_URL=\"%s\"\n" "${{ secrets.SUPABASE_POOL_URL }}" >> .env
          printf "INAT_BASE=\"%s\"\n" "${{ secrets.INAT_BASE }}" >> .env
          printf "ASSIGNMENT_IDS=\"%s\"\n" "${{ secrets.ASSIGNMENT_IDS }}" >> .env
          printf "RATE_LIMIT_RPS=\"%s\"\n" "${{ secrets.RATE_LIMIT_RPS }}" >> .env
          printf "NODE_ENV=\"production\"\n" >> .env
          echo ".env file created successfully."

      - name: Verify .env file structure (Masked)
        run: cat .env

      - name: Install dependencies
        run: npm install

      - name: Run Data Ingestion
        # The '-r dotenv/config' flag preloads environment variables from the .env file
        run: node -r dotenv/config ingest.mjs
