name: Ingest iNaturalist Data and Score

on:
  workflow_dispatch: # Allows manual triggering
  # schedule:
  #   - cron: '0 2 * * *' # Uncomment for scheduled runs (e.g., daily at 2 AM UTC)

# Security Best Practice: Restrict GITHUB_TOKEN permissions to the minimum required
permissions:
  contents: read

jobs:
  data-pipeline:
    name: Fetch, Ingest, and Process Data
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Safety measure for long-running or stuck jobs

    # =================================================================
    # CRITICAL FIX: Job-Level Environment Configuration
    # This maps GitHub Secrets into the OS Environment for all steps in this job.
    # =================================================================
    env:
      # Supabase API Access (Required by Supabase SDK)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # Database Connection String
      # CRITICAL: We map the Pooler URL (IPv4 compatible) to the variable the app expects.
      # This is required as the GitHub Actions environment cannot reliably connect to the Direct URL.
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_POOL_URL }}

      # iNaturalist Configuration
      INAT_BASE: ${{ secrets.INAT_BASE }}
      ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}

      # Application Settings
      RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use a stable LTS version (e.g., Node 20)
          cache: 'npm' # Cache dependencies to speed up future runs

      - name: Install dependencies
        # Best Practice: Use 'npm ci' (Clean Install) for reliable, reproducible builds in CI/CD
        run: npm ci

      # Robustness Check: Verify variables are present in the shell BEFORE running the application.
      - name: Verify Environment Availability
        run: |
          echo "Checking critical environment variables in the shell..."
          if [ -z "$SUPABASE_URL" ]; then echo "::error::SUPABASE_URL is missing."; exit 1; fi
          if [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then echo "::error::SUPABASE_SERVICE_ROLE_KEY is missing."; exit 1; fi
          if [ -z "$SUPABASE_DB_URL" ]; then echo "::error::SUPABASE_DB_URL (Pooler) is missing."; exit 1; fi
          echo "Environment ready."

      - name: Run Data Ingestion
        # The Node.js process now correctly inherits the environment variables defined at the job level.
        run: node ingest.mjs

      # Add subsequent steps (e.g., scoring) here. They will also inherit the environment variables.
      # - name: Run Scoring Calculation
      #   run: node score.mjs
