name: Ingest iNaturalist Data and Score

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  data-pipeline:
    name: Fetch, Ingest, and Process Data
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # =================================================================
    # CRITICAL FIX: Direct Environment Injection with Exact Variable Names
    # The script (ingest.mjs) reads directly from process.env and expects specific names.
    # =================================================================
    env:
      # The exact name expected by the script for the URL
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

      # CRITICAL: The script expects 'SUPABASE_SERVICE_KEY'.
      # We map the standard SUPABASE_SERVICE_ROLE_KEY secret to the name the script uses.
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # CRITICAL: The iNaturalist Project Slug required by the script
      INAT_PROJECT_SLUG: ${{ secrets.INAT_PROJECT_SLUG }}

      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js LTS (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        # Installs @supabase/supabase-js and node-fetch
        # Use 'npm ci' if you commit package-lock.json, otherwise 'npm install'
        run: npm install

      - name: Run Data Ingestion
        # The script will now find the variables directly in process.env
        run: node ingest.mjs
