name: SMOKE_PARSE_CHECK

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello
        run: echo "YAML parsed OK"
