name: Ingest iNaturalist Data and Score

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  data-pipeline:
    name: Build, Ingest, and Process Data
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Define the comprehensive environment block for the entire job.
    # This ensures variables are available for npm install, npm run build, and node execution.
    env:
      # --- Supabase SDK Variables ---
      # Standard backend names
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      # Framework conventions (Next.js, Vite) - Critical for Build-Time Embedding
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      # Generic Aliases
      SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # --- Database Connection Variables (Using the Pooler URL) ---
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_POOL_URL }}
      DATABASE_URL: ${{ secrets.SUPABASE_POOL_URL }}
      POSTGRES_URL: ${{ secrets.SUPABASE_POOL_URL }}

      # --- iNaturalist and Application variables ---
      INAT_BASE: ${{ secrets.INAT_BASE }}
      ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}
      RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js LTS (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      # =================================================================
      # CRITICAL FIX: Execute the Build Process
      # The application requires build-time embedding of environment variables.
      # The 'env' block defined at the job level ensures the variables are present here.
      # =================================================================
      - name: Build Application
        run: npm run build

      # =================================================================
      # Execution Step
      # =================================================================
      - name: Run Data Ingestion
        # The script now runs with the configuration correctly embedded.
        run: node ingest.mjs
