name: Ingest iNat and Score • vENVDEBUG3

on:
  workflow_dispatch:
  # While debugging you can comment the schedule out to reduce noise
  schedule:
    - cron: "*/30 * * * *"
  push:
    paths:
      - .github/workflows/ingest-and-score.yml
      - ingest.mjs
      - sql/**

permissions:
  contents: read

concurrency:
  group: ingest-and-score
  cancel-in-progress: true

jobs:
  ingest-and-score:
    runs-on: ubuntu-latest

    env:
      # HTTP API for the script
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      # aliases some scripts expect
      SB_URL: ${{ secrets.SUPABASE_URL }}
      SB_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # iNat / runtime knobs (if used)
      INAT_BASE: ${{ secrets.INAT_BASE }}
      ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}
      RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}

      # DB for psql steps
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_POOL_URL: ${{ secrets.SUPABASE_POOL_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (ok if none)
        run: |
          set -e
          if [ -f package-lock.json ]; then npm ci
          elif [ -f package.json ]; then npm i
          else echo "No package.json found; skipping"
          fi

      # ---- DEBUG (shell + node) ----
      - name: "Debug (shell): API secrets presence"
        run: |
          for k in SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY SB_URL SB_KEY INAT_BASE ASSIGNMENT_IDS RATE_LIMIT_RPS; do
            if [ -n "${!k:-}" ]; then echo "$k: SET"; else echo "$k: EMPTY"; fi
          done

      - name: "Debug (node): does Node see the env?"
        run: |
          node -e "console.log({
            SUPABASE_URL: !!process.env.SUPABASE_URL,
            SUPABASE_SERVICE_ROLE_KEY: !!process.env.SUPABASE_SERVICE_ROLE_KEY,
            SB_URL: !!process.env.SB_URL,
            SB_KEY: !!process.env.SB_KEY
          })"

      # ---- INGEST ----
      - name: Run iNat ingestion script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SB_URL: ${{ secrets.SUPABASE_URL }}
          SB_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          INAT_BASE: ${{ secrets.INAT_BASE }}
          ASSIGNMENT_IDS: ${{ secrets.ASSIGNMENT_IDS }}
          RATE_LIMIT_RPS: ${{ secrets.RATE_LIMIT_RPS }}
        run: |
          set -euo pipefail
          node ingest.mjs

      # ---- SQL / views ----
      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: "Debug (shell): DB secrets presence"
        run: |
          for k in SUPABASE_DB_URL SUPABASE_POOL_URL; do
            if [ -n "${!k:-}" ]; then echo "$k: SET"; else echo "$k: EMPTY"; fi
          done

- name: Choose DB URL and handshake
  id: pickdb
  run: |
    set -euo pipefail
    try() {
      url="$1"
      host=$(printf '%s' "$url" | sed -E 's@.*://[^@]*@//REDACTED@; s@^.*@&@')
      echo "Trying connection to: $host"
      # Show connection info and run a trivial query; verbose to surface error cause
      psql -4 "$url" -v VERBOSITY=verbose -c "\conninfo"
      psql -4 "$url" -Atc "select 1"
    }
    if [ -n "${SUPABASE_DB_URL:-}" ] && try "$SUPABASE_DB_URL"; then
      USE_URL="$SUPABASE_DB_URL"
    elif [ -n "${SUPABASE_POOL_URL:-}" ] && try "$SUPABASE_POOL_URL"; then
      USE_URL="$SUPABASE_POOL_URL"
    else
      echo "DB handshake failed. Re-check SUPABASE_DB_URL and SUPABASE_POOL_URL:"
      echo "• Use 'postgres' user and your **database password**."
      echo "• Include '?sslmode=require'."
      echo "• If password has special chars, URL-encode or use a simpler password."
      exit 1
    fi
    echo "use_url=$USE_URL" >> "$GITHUB_OUTPUT"
    echo "Handshake OK."

      - name: Generate SQL with correct id column
        run: |
          set -euo pipefail
          USE_URL="${{ steps.pickdb.outputs.use_url }}"
          ID_COL=$(psql -4 "$USE_URL" -Atc "
            select column_name
            from information_schema.columns
            where table_schema='public'
              and table_name='daily_scores'
              and column_name in ('student_id','roster_id','person_id')
            limit 1;")
          if [ -z "$ID_COL" ]; then
            echo 'Could not detect id column in public.daily_scores'; exit 1
          fi
          echo "Detected ID_COL=$ID_COL"
          if [ ! -f sql/leaderboard_views.template.sql ]; then
            echo "Missing sql/leaderboard_views.template.sql"; exit 1
          fi
          sed "s/__ID_COL__/$ID_COL/g" sql/leaderboard_views.template.sql > sql/_gen_leaderboard_views.sql
          echo "Generated sql/_gen_leaderboard_views.sql"

      - name: Apply / update views (idempotent)
        run: |
          set -euo pipefail
          USE_URL="${{ steps.pickdb.outputs.use_url }}"
          echo "Handshake details:"
          psql -4 "$USE_URL" -Atc "select current_user, current_database(), inet_server_addr(), inet_client_addr(), version();"
          psql -4 "$USE_URL" -v ON_ERROR_STOP=1 -f sql/_gen_leaderboard_views.sql
